config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'new_registrations' }
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  resources :users

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/landing_page'
  post 'payments/create'
  post 'simple_pages/thank_you'
  root 'simple_pages#index'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charly beheizbare Handschuhe</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="fixed-top navbar navbar-expand-md">
      <div class="container-mockup--left navbar-brand">
        <%= link_to image_tag("logo-charly.svg", alt: "Charly Logo"), root_path %>
      </div>
      <button class="container-mockup--right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse container-mockup--right navbar-collapse" id="navbarSupportedContent">
        <ul class="ml-auto navbar-nav">
          <li class="nav-item navbar-search nowrap">
            <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <%= form.submit 'Suche', class: "form__btn form__btn--primary navbar-search__submit" %>
              <%= form.text_field :q, id: 'q', value: params[:q], class: "img-responsive form__text-field navbar-search__text-field" %>
            <% end %>
            <li class="nav-item">&emsp;</li>
          </li>
        </ul>
        <ul class="ml-auto navbar-nav">
          <li class="nav-item"><%= active_link_to "Home", root_path, active: :exclusive, class: "nav-link" %></li>
          <li class="nav-item"><%= active_link_to "Produkte", products_path, class: "nav-link" %></li>
          <li class="nav-item"><%= active_link_to "Über\u00A0uns", simple_pages_about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= active_link_to "Kontakt", simple_pages_contact_path, class: "nav-link" %></li>
        </ul>
        &emsp;
        <ul class="ml-auto navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
            <button type="button" class="form__btn form__btn--primary"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></button>
          </li>
          <% else %>
          <li class="nav-item">
            <button type="button" class="form__btn form__btn--primary"><%= link_to('Login', new_user_session_path) %></button>
          </li>
          <% end %>
        </ul>
        &emsp;
        <% if alert %><div class="form__text-field message"><%= alert %></div><% end %>
        <% if notice %><div class="form__text-field message"><%= notice %></div><% end %>
      </div>
    </nav>
    <div class="container">

      <%= yield %>

    </div>
    <footer>
      Copyright &copy; 2018 Finsterwalder GmbH. Alle Rechte vorbehalten.
    </footer>
  </body>
</html>